Support ZPLY_COLOR environment variable

diff --git a/bin/git-refresh-patches b/bin/git-refresh-patches
--- a/bin/git-refresh-patches
+++ b/bin/git-refresh-patches
@@ -41,12 +41,11 @@ PATCH_REPO_DIR=$1
 SINCE=$2
 PATCHES_DIR=$PWD/.patches
 
-git zply-format $PATCHES_DIR $SINCE || die "git zply-format failed"
-
-if [[ -n $COLORIZE ]]; then
+if [[ $COLORIZE -eq 1 ]] || [[ $ZPLY_COLOR -eq 1 ]]; then
     COLOR_OPT=-c
 fi
 
+git zply-format $PATCHES_DIR $SINCE || die "git zply-format failed"
 git zply-sync $COLOR_OPT $PATCHES_DIR $PATCH_REPO_DIR
 SYNC_RET=$?
 if [[ $SYNC_RET -gt 1 ]]; then
