Add -c to refresh-patches

diff --git a/bin/git-refresh-patches b/bin/git-refresh-patches
--- a/bin/git-refresh-patches
+++ b/bin/git-refresh-patches
@@ -1,6 +1,6 @@
 #!/bin/bash
 CMD='git refresh-patches'
-USAGE="usage: $CMD [-b <branch>] [-h] [-pP] [-r <patch-repo-dir>] [-v] [since]"
+USAGE="usage: $CMD [-b <branch>] [-c] [-h] [-pP] [-r <patch-repo-dir>] [-v] [since]"
 VERSION=0.1
 
 function die() {
@@ -34,9 +34,10 @@ function version() {
 # MAIN
 read_config
 
-while getopts 'b:hpPr:v' opt; do
+while getopts 'b:chpPr:v' opt; do
     case $opt in
         b) BRANCH=$OPTARG;;
+        c) COMMIT=1;;
         h) help;;
         p) PULL_REPO=1;;
         P) PULL_REPO=0;;
@@ -79,5 +80,10 @@ SYNC_RET=$?
 if [[ $SYNC_RET -gt 1 ]]; then
     die "git zply-sync failed"
 fi
+
+if [[ $COMMIT -eq 1 ]]; then
+    git commit-patches || die "git commit-patches failed"
+fi
+
 rm -rf $PATCHES_DIR
 exit $SYNC_RET
