Usage should not use die

diff --git a/bin/git-zply-refresh b/bin/git-zply-refresh
--- a/bin/git-zply-refresh
+++ b/bin/git-zply-refresh
@@ -21,13 +21,21 @@
 #   0 - success
 #   1 - failure
 VERSION=0.1
+FORMAT_PATH=$PWD/.patches
 
 function version() {
     echo $VERSION
     exit 0
 }
 
+function cleanup() {
+    if [[ -e $FORMAT_PATH ]]; then
+        rm -rf $FORMAT_PATH
+    fi
+}
+
 function die() {
+    cleanup
     >&2 echo $@
     exit 1
 }
@@ -41,7 +49,8 @@ function check_patch_repo() {
 }
 
 function usage() {
-    die "usage: git zply-refresh [-h] [-v] <patch-repo-path> <since>"
+    >&2 echo $@ "usage: git zply-refresh [-h] [-v] <patch-repo-path> <since>"
+    exit 1
 }
 
 while getopts 'hv' opt; do
@@ -61,9 +70,10 @@ fi
 PATCH_REPO_PATH=$1
 check_patch_repo $PATCH_REPO_PATH
 SINCE=$2
-FORMAT_PATH=$PWD/.patches
 BASED_ON_HASH=`git show --pretty="%H" $SINCE`
-git zply-format -o $FORMAT_PATH $SINCE
-git zply-sync $FORMAT_PATH $PATCH_REPO_PATH
-git zply-commit -b $BASED_ON_HASH $PATCH_REPO_PATH
-rm -rf $FORMAT_PATH
+
+git zply-format -o $FORMAT_PATH $SINCE || die "git zply-format failed"
+git zply-sync $FORMAT_PATH $PATCH_REPO_PATH || die "git zply-sync failed"
+git zply-commit -b $BASED_ON_HASH $PATCH_REPO_PATH || die "git zply-commit failed"
+
+cleanup
