Add -o to zply-format

diff --git a/bin/git-refresh-patches b/bin/git-refresh-patches
--- a/bin/git-refresh-patches
+++ b/bin/git-refresh-patches
@@ -60,7 +60,7 @@ if [[ -n $BRANCH ]]; then
     BRANCH_OPT="-b $BRANCH"
 fi
 
-git zply-format $PATCHES_DIR $SINCE || die "git zply-format failed"
+git zply-format -o $PATCHES_DIR $SINCE || die "git zply-format failed"
 git zply-sync $BRANCH_OPT -r $ZPLY_PATCH_REPO_DIR $PATCHES_DIR
 SYNC_RET=$?
 if [[ $SYNC_RET -gt 1 ]]; then
diff --git a/bin/git-zply-format b/bin/git-zply-format
--- a/bin/git-zply-format
+++ b/bin/git-zply-format
@@ -1,7 +1,8 @@
 #!/bin/bash
 CMD="git zply-format"
-USAGE="usage: $CMD [-h] [-v] <patches-dir> <since>"
+USAGE="usage: $CMD [-h] [-o <output-dir>] [-v] <since>"
 VERSION=0.1
+OUTPUT_DIR=.
 
 function die() {
     >&2 echo "[$CMD error]: $@"
@@ -34,20 +35,21 @@ function version() {
 # MAIN
 read_config
 
-while getopts 'hv' opt; do
+while getopts 'ho:v' opt; do
     case $opt in
         h) help;;
+        o) OUTPUT_DIR=$OPTARG;;
         v) version;;
         *) die_usage;;
     esac
 done
 shift $(($OPTIND - 1))
-if [[ -z $1 ]] || [[ -z $2 ]]; then
+
+if [[ -z $1 ]]; then
     die_usage
 fi
 
-PATCHES_DIR=$1
-SINCE=$2
+SINCE=$1
 
 # Convert `since` to a commit hash
 git rev-parse -q --verify $SINCE > /dev/null || die "Revision $SINCE not found"
@@ -57,17 +59,17 @@ if [[ -e .git/rebase-apply ]]; then
     die "Cannot format patches while a rebase is in progress (in the middle of git am?)"
 fi
 
-git format-patch -kpo $PATCHES_DIR $SINCE > /dev/null || die "git format-patch failed"
+git format-patch -kpo $OUTPUT_DIR $SINCE > /dev/null || die "git format-patch failed"
 
 # Make sure we generated at least one patch file
-ls $PATCHES_DIR/*.patch 2>&1 > /dev/null
+ls $OUTPUT_DIR/*.patch 2>&1 > /dev/null
 if [[ $? -ne 0 ]]; then
     die "No patch files generated (did you forget to run git am?)"
 fi
 
-for patch in `ls $PATCHES_DIR/*.patch`; do
+for patch in `ls $OUTPUT_DIR/*.patch`; do
     git zply-fixup $patch > $patch.tmp || die "git zply-fixup failed"
     mv $patch.tmp $patch
 done
 
-echo $SINCE > $PATCHES_DIR/.based-on
+echo $SINCE > $OUTPUT_DIR/.based-on
