Simplifying things by not sharing code between commands

diff --git a/bin/git-zply-format b/bin/git-zply-format
--- a/bin/git-zply-format
+++ b/bin/git-zply-format
@@ -1,12 +1,33 @@
+#!/bin/bash
 CMD='git zply-format'
+VERSION=0.1
+
+function die() {
+    >&2 echo "[$CMD error]: $@"
+    exit 1
+}
 
 function usage() {
     >&2 echo $@ "usage: $CMD [-h] [-v] <patches-dir> <since>"
     exit 1
 }
 
-parse_std_opts
-verify_two_args
+function version() {
+    echo $VERSION
+    exit 0
+}
+
+while getopts 'hv' opt; do
+    case $opt in
+        h) usage;;
+        v) version;;
+        *) usage;;
+    esac
+done
+shift $(($OPTIND - 1))
+if [[ -z $1 ]] || [[ -z $2 ]]; then
+    usage
+fi
 
 PATCHES_DIR=$1
 SINCE=$2
diff --git a/bin/git-zply-sync b/bin/git-zply-sync
--- a/bin/git-zply-sync
+++ b/bin/git-zply-sync
@@ -1,17 +1,50 @@
+#!/bin/bash
 CMD='git zply-sync'
-RET=0
+VERSION=0.1
+
+function die() {
+    >&2 echo "[$CMD error]: $@"
+    exit 1
+}
+
+function realpath {
+    echo $(cd $(dirname $1); pwd)/$(basename $1);
+}
 
 function usage() {
     >&2 echo $@ "usage: $CMD [-h] [-v] <patches-dir> <patch-repo-dir>"
     exit 1
 }
 
-parse_std_opts
-verify_two_args
+
+function version() {
+    echo $VERSION
+    exit 0
+}
+
+while getopts 'hv' opt; do
+    case $opt in
+        h) usage;;
+        v) version;;
+        *) usage;;
+    esac
+done
+shift $(($OPTIND - 1))
+
+if [[ -z $1 ]] || [[ -z $2 ]]; then
+    usage
+fi
 
 PATCHES_DIR=`realpath $1`
 PATCH_REPO_DIR=`realpath $2`
-check_patch_repo $PATCH_REPO_DIR
+
+if [[ ! -e $PATCH_REPO_DIR ]]; then
+    die "Patch repo directory not found"
+elif [[ ! -e $PATCH_REPO_DIR/.git ]]; then
+    die "Patch repo is not a git repo (did you git init it?)"
+fi
+
+RET=0
 
 # Copy patches into patch repo
 for patch in `ls $PATCHES_DIR/*.patch`; do
@@ -44,7 +77,7 @@ for patch in `ls *.patch`; do
         git add $patch_basename || die "git add failed for $patch_basename"
     else
         echo "Removing unused patch $patch_basename"
-        git rm $patch_basename || die "git rm failed for $patch_basename"
+        git rm $patch_basename > /dev/null || die "git rm failed for $patch_basename"
         RET=2
     fi
 done
