Better error messages

diff --git a/bin/git-zply-commit b/bin/git-zply-commit
--- a/bin/git-zply-commit
+++ b/bin/git-zply-commit
@@ -1,5 +1,6 @@
 #!/bin/bash
 # Commit all patches to patch repo
+CMD='git zply-commit'
 VERSION=0.1
 
 function version() {
@@ -8,7 +9,7 @@ function version() {
 }
 
 function die() {
-    >&2 echo $@
+    >&2 echo "[$CMD error]: $@"
     exit 1
 }
 
@@ -18,9 +19,9 @@ function realpath {
 
 function check_patch_repo() {
     if [[ ! -e $1 ]]; then
-        die "error: Patch repo directory not found"
+        die "Patch repo directory not found"
     elif [[ ! -e $1/.git ]]; then
-        die "error: Patch repo is not a git repo (did you git init it?)"
+        die "Patch repo is not a git repo (did you git init it?)"
     fi
 }
 
diff --git a/bin/git-zply-refresh b/bin/git-zply-refresh
--- a/bin/git-zply-refresh
+++ b/bin/git-zply-refresh
@@ -20,6 +20,7 @@
 #
 #   0 - success
 #   1 - failure
+CMD='git zply-refresh'
 VERSION=0.1
 FORMAT_PATH=$PWD/.patches
 
@@ -36,15 +37,15 @@ function cleanup() {
 
 function die() {
     cleanup
-    >&2 echo $@
+    >&2 echo "[$CMD error]: $@"
     exit 1
 }
 
 function check_patch_repo() {
     if [[ ! -e $1 ]]; then
-        die "error: Patch repo directory not found"
+        die "Patch repo directory not found"
     elif [[ ! -e $1/.git ]]; then
-        die "error: Patch repo is not a git repo (did you git init it?)"
+        die "Patch repo is not a git repo (did you git init it?)"
     fi
 }
 
diff --git a/bin/git-zply-sync b/bin/git-zply-sync
--- a/bin/git-zply-sync
+++ b/bin/git-zply-sync
@@ -1,4 +1,5 @@
 #!/bin/bash
+CMD='git zply-sync'
 VERSION=0.1
 
 function version() {
@@ -7,7 +8,7 @@ function version() {
 }
 
 function die() {
-    >&2 echo $@
+    >&2 echo "[$CMD error]: $@"
     exit 1
 }
 
@@ -17,9 +18,9 @@ function realpath {
 
 function check_patch_repo() {
     if [[ ! -e $1 ]]; then
-        die "error: Patch repo directory not found"
+        die "Patch repo directory not found"
     elif [[ ! -e $1/.git ]]; then
-        die "error: Patch repo is not a git repo (did you git init it?)"
+        die "Patch repo is not a git repo (did you git init it?)"
     fi
 }
 
