Add -b to git-zply-commit

diff --git a/git-zply-format b/git-zply-format
--- a/git-zply-format
+++ b/git-zply-format
@@ -16,8 +16,7 @@ SINCE=$2
 echo "Formatting patches..."
 git format-patch -kpo $FORMAT_PATH $SINCE > /dev/null || die "git format-patch failed"
 
-echo "Fixing up patches..."
 for patch in `ls $FORMAT_PATH/*.patch`; do
-    git zply-fixup $patch > $patch.tmp || die "git fixup-patch failed"
+    git zply-fixup $patch > $patch.tmp || die "git zply-fixup failed"
     mv $patch.tmp $patch
 done
