Better output

diff --git a/git-save-patch b/git-save-patch
--- a/git-save-patch
+++ b/git-save-patch
@@ -23,7 +23,11 @@ BASED_ON_HASH=`git show --pretty="%H" $SINCE`
 
 # Create patch series
 rm -rf $PATCH_TMP_DIR
-git format-patch -kpo $PATCH_TMP_DIR $SINCE
+
+echo "Formatting patches..."
+git format-patch -kpo $PATCH_TMP_DIR $SINCE > /dev/null || die "git format-patch failed"
+
+echo "Copying patches into patch repo..."
 for patch in `ls $PATCH_TMP_DIR/*.patch`; do
     ../zply/git-fixup-patch $patch > $patch.tmp || die "git fixup-patch failed"
     mv $patch.tmp $patch
@@ -35,6 +39,8 @@ for patch in `ls $PATCH_TMP_DIR/*.patch`; do
         ../zply/git-diff-patch $patch $REPO_PATCH > /dev/null
         if [[ $? -eq 0 ]]; then
             COPY_PATCH=0
+        elif [[ $? -ne 1 ]]; then
+            die "git diff-patch failed"
         fi
     fi
     if [[ $COPY_PATCH -eq 1 ]]; then
@@ -42,12 +48,12 @@ for patch in `ls $PATCH_TMP_DIR/*.patch`; do
     fi
 done
 
-pushd $PATCH_REPO_PATH
+pushd $PATCH_REPO_PATH > /dev/null
 
 # Clean up any vestigial patches
+echo "Cleaning up vestigial patches..."
 for patch in `ls *.patch`; do
     patch_basename=`basename $patch`
-    echo $PATCH_TMP_DIR/$patch_basename
     if [[ ! -e $PATCH_TMP_DIR/$patch_basename ]]; then
         git rm $patch_basename
         if [[ $? -ne 0 ]]; then
@@ -57,6 +63,7 @@ for patch in `ls *.patch`; do
 done
 
 # Commit
+echo "Commiting patches..."
 git add *.patch
 cat > .tmp-commit-msg <<-EOF
 Saving patches...
@@ -65,7 +72,8 @@ Based-On: $BASED_ON_HASH
 EOF
 # -t would abort the commit if the message was not edited; we don't want to
 # require that in all cases, so using -eF instead
-git commit -eF .tmp-commit-msg
+git commit -qeF .tmp-commit-msg
 rm .tmp-commit-msg
-popd
+popd > /dev/null
 rm -rf $PATCH_TMP_DIR
+echo "Done."
